#########
# Fixes #
#########

["cups-2.4.10"]
cve = "CVE-2022-26691"
comment = "Fixed in cups-2.4.2"

##############
# Mismatches #
##############

["async"]
cve = [
    "CVE-2021-43138"  # Refers to "caolan/async for Node.js"
]
comment = "Refers to another program"

["ShellCheck"]
cve = [
    "CVE-2021-28794"  # Refers to "ShellCheck VSCode Extension"
]
comment = "Refers to another program"

