##############
# Mismatches #
##############

["async"]
cve = [
    "CVE-2021-43138"  # Refers to "caolan/async for Node.js"
]
comment = "Refers to another program"

["ShellCheck"]
cve = [
    "CVE-2021-28794"  # Refers to "ShellCheck VSCode Extension"
]
comment = "Refers to another program"

